FROM python:3.12-slim

#crear carpeta de trabajo
WORKDIR /app
#copia de requerimientos
COPY requeriments.txt .

#instalar requerimientos
RUN pip install --no-cache-dir -r requeriments.txt

#copiar el codigo del proyecto
COPY ./app ./app

#Exponer el puerto
EXPOSE 5000

#Comandos para ejecutar FASTAPI
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","5000","--reload"]