FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Variable de entorno que uso para conectar con FastAPI
ENV FASTAPI_URL=http://fastapi:5000

CMD ["python", "app.py"]